### ISSUE TITLE
Leaked paramiko ssh connection threads prevent rho from exiting

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#17]
https://github.com/candlepin/rho/issues/15

- [ ] Validate still an issue with `rho-2.0`
- [ ] Provide resolution

**Comment by noahl** [comment]
I think this issue is from the rho 1 era, where rho used paramiko. It *might* still be possible to make this happen with rho 2, if you configure Ansible to use paramiko and trip over a bug there, but it would be a completely different issue. I also don't see how we could realistically test for "maybe there's a paramiko bug in Ansible somewhere".

I think we should close this. @chambridge do you agree?

**Comment by chambridge** [comment]
@noahl Looking at the Ansible doc around [transport](http://docs.ansible.com/ansible/intro_configuration.html#transport), it does look like this is still a potential issue as Ansible can "fallback" to using paramiko. But I agree we should really only focus on it if a reproducible bug is provided using rho 2.0 code base.

The only suggestion I would have before closing this is we could update our python dependency to be explicit that we require Ansible 2.x, by updating the [requirements.txt](https://github.com/quipucords/rho/blob/master/requirements.txt#L1) with a constraint. As I believe Ansible 2.0 is when they default moved to using OpenSSH (although I think it was available for use from 1.3 on).

Thoughts?

**Comment by noahl** [comment]
I've been thinking about this. People *should* have recent Ansibles, and I'm fine updating the dependency if we're getting features that we need, but it doesn't make sense to me to update the dependency for this issue. In the context of rho 2, I think this bug is so broadly stated that we can never prove it won't happen, but we also have no evidence that it will.

From my reading of the bug it looked like the issue was with how rho 1 was using Paramiko, not Paramiko itself, so I don't think that an old Ansible necessarily would have the same problem.

**Comment by chambridge** [comment]
I'm good with closing this as `pip` will install the latest module by default so no real need to update the dependency explicitly.
