### ISSUE TITLE
Update rho Quick Start guide: gather info for 1st draft

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#198]
## Type:
- Enhancement
___

## Description:
The previous release of `rho` has an associated quick start guide. The contents of the quick start guide needs to be refreshed with the updates associated with the latest release.

**Comment by jlprevatt-zz** [comment]
@chambridge changed title to track smaller chunk of work

**Comment by noahl** [comment]
Hi Jamie,

Following up on our meeting, here are a few more things I found. Please let me know if you'd rather have this information somewhere else!

In the quick start guide:
- `rho initconfig` goes away. No need for that in rho 2.0.
- In `rho profile add`, the `--range` argument should be `1.2.3.[0:255]`, which gives an accurate picture of how we describe IP address ranges (this might change again if we support [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing).
- The `rho scan` command should be `rho scan --profile mynetwork --reportfile=report.csv`.

Thanks again for all of your hard work on this guide!

**Comment by noahl** [comment]
Oh, and instead of asking the users to submit `pack-scan.csv`, we should ask them to submit `report.csv`.

**Comment by noahl** [comment]
And one question - there's a document called `COPY rho_2016_Mar_28.pdf`. It looks a lot like a man page. Is that actually a man page that has been formatted as PDF? I have some feedback on it, but if it's a man page then the feedback isn't relevant any more anyway.

**Comment by jlprevatt-zz** [comment]
Noah, thanks for capturing some of the things we talked about here, as a way to double-check my notes.
RE your comment on IP addresses:

- I'm not an IP address expert at all, but I'm not familiar with that particular notation 1.2.3.[0:255]. Tried Googling on the use of brackets in the notation, but kept hitting things like the IPv6 notation that uses two colons. Because I couldn't figure out what it was, I couldn't figure out how to take a stab at editing it into a doc example. (You don't have to explain the syntax here--the end result is getting an example with an allowable IP range (Mark specifically wants range per his comments).)

- The reason I can't use your information as-is and have to change it is that you are not supposed to use mocked-up IP addresses in documentation (or examples in code). There are specific ranges of IP addresses reserved for documentation examples. Here's more info than you probably want on this:
[general reserved IPv4 addresses info](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml)
[reserved doc IP adddresses info](https://tools.ietf.org/html/rfc5737)

- Per those standards, there are three ranges of IPv4 notation (assuming that's what we want to use) that are reserved for doc:
192.0.2.0/24 and 198.51.100.0/24 and 203.0.113.0/24

- So if you can translate your suggested example for a range (with the bracket syntax) into one using the allowable addresses, that would be great. Adding up your comments plus Mark's comments, I will add a guess here and you can correct if anything is wrong. **To search the 192.0.2.0/24 subnet, you would add 192.0.2.[0:255] as the value for the range.** (Mark's example used 1:254; doing more Googling, that's actually the "allowable" addresses?)

- Thanks for looking at this long comment.

**Comment by jlprevatt-zz** [comment]
RE your comment about the  COPY rho_2016_Mar_28.pdf guide, that guide was done under an effort separate from SEAP (I think someone in sales) and is the doc that Mark says contains "too much" info for customers and confuses them. I put some of the extra tips from that guide into my QSG 1st draft, but Mark asked for some of those to be taken out again as TMI. The info might have been taken directly from the man page and swizzled. I know who in CCS helped the sales team with that project, but I didn't ask that specific question. As part of the plan Mark and I put together for Rho 2.0 delivery, that doc will be removed from the customer portal article about Rho and the updated 2.0 QSG will replace it. The updated QSG does contain a note about reviewing the Rho man page for more information about commands. Less info, but less opportunity for customers to confuse themselves.

**Comment by noahl** [comment]
@jlprevatt I don't know if the bracket notation has a name. I haven't encountered it anywhere other than Ansible.

I didn't know there were IP address ranges reserved for documentation! That was very cool; thank you for teaching me. I think you've translated the example correctly - `192.0.2.[0:255]` should scan the entire `192.0.2.0/24` subnet.

Since we're going to replace the other document with the 2.0 QSG, it sounds like I don't need to spend more time looking at that other document. I like the idea of having the QSG and then pointing customers to the man page for more information - fewer sources of information are fewer things for us to keep up to date and in sync.

Thanks again!

**Comment by chambridge** [comment]
Based on last weeks output. I assume this is closed. Feel free to reopen if that is not correct.
