### ISSUE TITLE
Do we still want a rho-specific repository?

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#228]
The old quick start references http://repos.fedorapeople.org/repos/candlepin/rho/epel-rho.repo , which seems to a repository description for `epel-rho`, which is a repository that only holds the rho package. Do we still want that, or do we want people to just use regular EPEL?

**Comment by noahl** [comment]
@jlprevatt this will determine the first part of the quick start guide

**Comment by elyezer** [comment]
If epel will always be needed, even in fedora, thank I think it makes sense to add to epel itself.

I am not sure about if we are required to support running on fedora. Because I don't think  epel is a repo that people usually add to a fedora system. That said, in this case, is better to have a repo only for RHO.

Take my comment with a grain of salt because I don't have a good experience on packaging and its good practices.

**Comment by noahl** [comment]
Looking at the issues we have on deck right now, I think we can safely delay this question until after we release Rho 2.0. Let's put it in the backlog and resolve it along with #194 .

**Comment by jlprevatt-zz** [comment]
Since this issue started as a placeholder for determining whether steps 1-3 of the install section of the Rho QSG are still valid, can we add some extra info to clarify the decision here?

So: For the 2.0 code delivery Sept. 1, will the customers still get Rho with the same steps/same path as described in the current QSG? Thanks.

**Comment by chambridge** [comment]
rho 0.0.28-5 included into EPEL. Closing out this issue.
