### ISSUE TITLE
Use the same bug reporting information?

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#24]
Should the bug reporting information stay the same?
https://github.com/quipucords/rho/tree/issues/3#known-issues

**Comment by jlalbertson** [comment]
My opinion is that we should update this to point people to the GitHub issues instead, but I'm interested in other opinions on this. 

My reasoning: We may want to consider another tool for tracking bugs when we move over to Sonar, but since this is already established for RHO, I think it makes sense to just keep it there. Which also keeps us from having to look in multiple places for issues.

**Comment by noahl** [comment]
I agree with @jlalbertson . Looks like everyone is thumbs up so far.

**Comment by chambridge** [comment]
Ok. I will update the README Issues section to inform users to open issues here instead of bugzilla.
