### ISSUE TITLE
Review rho man documentation

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#272]
## Specify type:
- Enhancement
___

## Description:
Review and update latest man doc for rho
___

**Comment by jlprevatt-zz** [comment]
Did hard copy edit, went over some general concepts (not line-by-line) about these with Noah. With issue #301 "Move man page to different format" now open, the larger issue of getting the edits in, with what tool, and with what amount of resource (CCS and dev) is still partially TBD. Noah and Jamie are scheduled to pick this up next week to see if getting it done in the confines of the next sprint is realistic.

Because the CCS task to review/edit is complete, going to move this into Done status.
