### ISSUE TITLE
Analyze JBoss Scanner code base for reusable abstractions

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#46]
JBoss Scanner https://github.com/mdvickst/jboss-scanner

- [x] How do we abstract out the usage of the secure vault
- [x] How do we modularize the scanning for JBoss

**Comment by noahl** [comment]
My full notes are at https://docs.google.com/a/redhat.com/document/d/12ENI0jZ12OA4pDSuV0jD-RqEk-rgxphPODw6xXK5nws/edit?usp=sharing . 

To summarize, JBoss Scanner already uses Ansible as a way to run its scanning code on remote machines. This is great for us, because it means that as soon as we can handle running more than one Ansible fact-collection module, we can more or less plug in the JBoss Scanner modules (I'm not sure if they output their results as facts right now, but they were clearly designed to based on the comments).

There is also some other code that may be useful, like doing user interaction with command-line menus and using the Ansible Vault. Using this code is a separate project from using JBoss Scanner's Ansible modules.

**Comment by noahl** [comment]
I filed #48 to be about the Ansible modules specifically.

**Comment by noahl** [comment]
@chambridge I don't want to mark this complete until you have a chance to look at my doc; there might be more to do.

**Comment by chambridge** [comment]
Thanks for the summary doc @noahl. Reviewed your comments and the structure of the JBoss Scanner code base. Looks like the modules work you began prototyping may be promising. However, looking further at the code we maybe able to utilize the ansible-vault api directly (e.g. https://github.com/jptomo/ansible-vault/blob/master/ansible_vault/api.py) within our code instead of kick off a subprocess as is currently done in the scanner code. We may also be able to drop some of the additional crypto classes that are being used to encypt the config and just encrypt everything with ansible-vault.
