### ISSUE TITLE
Add logging and debug capabilities in RHO

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#56]
RHO should not send verbose program execution flow standard out. It should log this information.
Additionally, RHO should provide a *verbose* flag (similar to Ansible) that helps to provide more detailed information (and triggers more data collection from Ansible as well).

**Comment by dozdowski** [comment]
I've been directed to Ellen Newlands - who's also part of Xav's team - for information on common logging and log formatting.  She's going to set up a meeting to educate me on what they're doing and how to build our logging.  Hopefully we get ahead of this one, and our logs will be ready-made for integration with CloudForms and the rest of the management engines.  (I mention CFME largely because Loic was featuring common logging  and log display as featured in an upcoming CloudForms release)

**Comment by chambridge** [comment]
Logging and debug to be added to rho will be dealt with a case by case basis from no on, as we have already added some of this capability. Logging a debug for sonar will be part of initial project development. Closing this catch all issue.
